# Generated by Django 2.2.4 on 2019-08-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('LOCATION_NAME', models.CharField(max_length=30)),
                ('SITE_NAME', models.CharField(max_length=255)),
                ('CONTACT', models.CharField(max_length=20)),
                ('ADDRESS', models.CharField(max_length=255)),
                ('SITE_SUBURB', models.CharField(max_length=100)),
                ('STATE', models.CharField(max_length=3)),
                ('POSTCODE', models.IntegerField(null=True)),
                ('URL', models.CharField(max_length=255, null=True)),
                ('EMAIL_ADDRESS', models.EmailField(max_length=100)),
                ('LATITUDE', models.FloatField(max_length=100, null=True)),
                ('LONGITUDE', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
